version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/libs/postgresql/data/
    env_file:
      - .env
    networks:
      - my-network
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             python manage.py fill_db &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./staticfiles:/var/www/staticfiles
      - ./back-static:/var/www/back-static
      - ./media:/var/www/media
    environment:
      - TZ=Asia/Bishkek
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - db
    env_file:
      - .env



volumes:
  postgres_data:
  static_volume:
  media_volume:
  staticfiles_volume:

networks:
  my-network:
