version: '3'

services:

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             python manage.py fill_db &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - staticfiles_volume:/app/staticfiles
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bishkek
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env

volumes:
  .:
  postgres_data:
  static_volume:
  media_volume:
  staticfiles_volume:
