# Generated by Django 5.0.6 on 2024-07-03 12:08

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                        verbose_name="Дата последнего обновления",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default="default_image.jpg",
                        help_text="Загрузите изображение для иконки преимущества",
                        null=True,
                        upload_to="benefit_icons/",
                        verbose_name="Иконка преимущества",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название преимущества",
                        max_length=255,
                        verbose_name="Название преимущества",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание преимущества (необязательно)",
                        null=True,
                        verbose_name="Описание преимущества",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество (Practicum)",
                "verbose_name_plural": "Преимущества (Practicum)",
            },
        ),
        migrations.CreateModel(
            name="FounderSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                        verbose_name="Дата последнего обновления",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Укажите ФИО руководителя",
                        max_length=255,
                        unique=True,
                        verbose_name="ФИО руководителя",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default_image.jpg",
                        help_text="Загрузите изображение основателя (необязательно)",
                        null=True,
                        upload_to="founder_images/",
                        verbose_name="Изображение основателя",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание раздела (необязательно)",
                        null=True,
                        verbose_name="Описание раздела",
                    ),
                ),
                (
                    "paragraphs",
                    models.TextField(
                        blank=True,
                        help_text="Используйте красную строку для разделения параграфов (макс. 6)",
                        null=True,
                        verbose_name="Параграфы раздела",
                    ),
                ),
            ],
            options={
                "verbose_name": "Руководитель",
                "verbose_name_plural": "Руководители",
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                        verbose_name="Дата последнего обновления",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите полное имя потенциального клиента",
                        max_length=255,
                        verbose_name="Полное имя",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Введите номер телефона клиента",
                        max_length=128,
                        region=None,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите электронную почту клиента",
                        max_length=254,
                        verbose_name="Электронная почта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                        verbose_name="Дата последнего обновления",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="Введите имя автора отзыва",
                        max_length=255,
                        verbose_name="Автор отзыва",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Введите текст отзыва (необязательно)",
                        null=True,
                        verbose_name="Текст отзыва",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
