# Generated by Django 5.0.6 on 2024-07-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundersection',
            name='paragraphs',
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата последнего обновления')),
                ('paragraphs', models.TextField(blank=True, help_text='Используйте красную строку для разделения параграфов (макс. 6)', null=True, verbose_name='Параграфы раздела')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='practicum.foundersection', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Параграфы',
            },
        ),
    ]
