# Generated by Django 5.0.6 on 2024-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicum', '0002_remove_foundersection_paragraphs_paragraphs'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата последнего обновления')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(help_text='Основной текст новости', verbose_name='Текст')),
                ('image', models.ImageField(blank=True, default='default_image.jpg', help_text='Загрузите изображение основателя (необязательно)', null=True, upload_to='news/', verbose_name='Изображение новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
