# Generated by Django 5.0.6 on 2024-07-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicum', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Укажите рейтинг новости (от 0 до 10)', null=True, verbose_name='Рейтинг курса'),
        ),
    ]
