# Generated by Django 5.0.6 on 2024-07-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academy",
            "0002_alter_advantage_icon_alter_course_background_person_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="icon",
            field=models.ImageField(
                blank=True,
                default="default_image.jpg",
                help_text="Загрузите изображение для иконки курса",
                null=True,
                upload_to="course_icons/",
                verbose_name="Иконка курса",
            ),
        ),
    ]
