# Generated by Django 5.0.6 on 2024-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_alter_course_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="icon",
            field=models.ImageField(
                blank=True,
                default="/static/default_image.jpg",
                help_text="Загрузите изображение для иконки курса",
                null=True,
                upload_to="course_icons/",
                verbose_name="Иконка курса",
            ),
        ),
    ]
