# Generated by Django 5.0.6 on 2024-07-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_alter_course_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advantage",
            name="icon",
            field=models.ImageField(
                blank=True,
                default="default_image.jpg",
                help_text="Загрузите иконку преимущества",
                null=True,
                upload_to="advantage_icons/",
                verbose_name="Иконка преимущества",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="background_person",
            field=models.ImageField(
                blank=True,
                default="default_image.jpg",
                help_text="Загрузите изображение для фона курса",
                null=True,
                upload_to="course_backgrounds/",
                verbose_name="Изображение для фона",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="icon",
            field=models.ImageField(
                blank=True,
                default="default_image.jpg",
                help_text="Загрузите изображение для иконки курса",
                null=True,
                upload_to="course_icons/",
                verbose_name="Иконка курса",
            ),
        ),
    ]
