# Generated by Django 5.0.6 on 2024-07-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutsourcingBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                        verbose_name="Дата последнего обновления",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название преимущества",
                        max_length=255,
                        unique=True,
                        verbose_name="Название преимущества",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание преимущества",
                        null=True,
                        verbose_name="Описание преимущества",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
            },
        ),
        migrations.CreateModel(
            name="OutsourcingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                        verbose_name="Дата последнего обновления",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название услуги",
                        max_length=255,
                        unique=True,
                        verbose_name="Название услуги",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание услуги",
                        null=True,
                        verbose_name="Описание услуги",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default="default_image.jpg",
                        help_text="Загрузите иконку услуги",
                        null=True,
                        upload_to="outsourcing_service_icons/",
                        verbose_name="Иконка услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="OutsourcingSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                        verbose_name="Дата последнего обновления",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название умения",
                        max_length=255,
                        unique=True,
                        verbose_name="Название умения",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default="default_image.jpg",
                        help_text="Загрузите иконку умения",
                        null=True,
                        upload_to="outsourcing_skill_icons/",
                        verbose_name="Иконка умения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Умение",
                "verbose_name_plural": "Умения",
            },
        ),
    ]
